apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment
  labels:
    app:docker-k8s-demo
Spec:
  replicas: 1
  selector:
     matchLabels:
       app:docker-k8s-demo
  template:
     metadat:
       labels:
         app: docker-k8s-demo
     spec:
       containers:
       -name: docker-k8s-demo
        image:vinodroyiit2002/docker-demo
        ports:
        -containerPort: 8080